#!/bin/bash

# A script that will create an Ubuntu VM in Azure

# Define variables that will be used in the create vm function
RESOURCE_GROUP_NAME=ubuntuVM
LOCATION=eastus
VM_NAME=ubuntu
VM_IMAGE= 0001-com-ubuntu-minimal-lunar
ADMIN_USERNAME=azureuser
PUBLISHER=canonical

# Create resource group
create_resource_group() {
   echo "Creating resouce group: $RESOURCE_GROUP_NAME in $LOCATION"
   az group create --name $RESOURCE_GROUP_NAME --location $LOCATION | grep provisioningState 
}

# List all resource groups
list_resource_groups() {
    az group list -o table
}

# Create the virtual machine
create_virtual_machine () {
    echo "Creating virtual machine: $VM_NAME in $$LOCATION"
    az vm create -g $RESOURCE_GROUP_NAME -n $VM_NAME --image $VM_IMAGE --admin-username $ADMIN_USERNAME --generate-ssh-keys -l $LOCATION --public-ip-sku Standard | grep provisioningState
}


create_resource_group
list_resource_groups
create_virtual_machine
