#!/bin/bash

# A script that will create an Ubuntu VM in Azure

# Define variables that will be used in the create vm function
RESOURCE_GROUP_NAME=ubuntuVM
LOCATION=eastus
VM_NAME=ubuntu
VM_IMAGE=UbuntuLTS
ADMIN_USERNAME=azureuser
PUBLISHER=canonical

# Create resource group
create_resource_group() {
   echo "Creating resouce group: $RESOURCE_GROUP_NAME in $LOCATION"
   az group create --name $RESOURCE_GROUP_NAME --location $LOCATION | grep provisioningState 
}

# List all resource groups
list_resource_groups() {
    az group list -o table
}

# Create the virtual machine
create_virtual_machine () {
    echo "Creating virtual machine: $VM_NAME in $LOCATION"
    az vm create -g $RESOURCE_GROUP_NAME -n $VM_NAME --image $VM_IMAGE --admin-username $ADMIN_USERNAME --generate-ssh-keys -l $LOCATION --public-ip-sku Standard | grep provisioningState
}

# Open port 80 for web traffic
open_port_80() {
    az vm open-port --port 80 --resource-group $RESOURCE_GROUP_NAME --name $VM_NAME
}

# SSH into the virtual machine
ssh_into_vm() {
    VM_IP_ADDRESS=$(az vm show --name $VM_NAME --resource-group $RESOURCE_GROUP_NAME --query 'publicIps' --output tsv)
    echo "VM IP Address: $VM_IP_ADDRESS"
    ssh azureuser@$VM_IP_ADDRESS
}

# Install Apache, MySQL, PHP (LAMP)
install_lamp() {
    sudo apt update && sudo apt install lamp-server^
}

# Verify and secure Apache, MySQL, PHP
verify_apache_mysql() {
    apache2 -v
    mysql -V
    sudo mysql_secure_installation
    php -v
}

# Uncomment the required functions to execute
#create_resource_group
#list_resource_groups
#create_virtual_machine
#open_port_80
ssh_into_vm
install_lamp
verify_apache_mysql
